2018-06-29 11:14:13,438 [django.request:93] [base:get_response] [WARNING]- Not Found: /
2018-06-29 11:14:32,678 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:14:33,058 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:33,499 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/commons.js
2018-06-29 11:14:58,797 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-06-29 11:48:11,403 [HttpRunnerManager:151] [operation:add_case_data] [INFO]- 的用例添加成功: {'test': {'request': {'method': 'POST', 'url': ''}, 'name': '的'}}
2018-06-29 11:48:48,076 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:34:18,047 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:18,057 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:18,268 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,270 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,276 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,278 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,296 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:18,299 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:18,352 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:18,364 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:18,370 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:18,383 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:18,578 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/favicon.ico
2018-07-02 13:34:21,442 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:21,445 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,449 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:21,484 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,487 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,492 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:21,508 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:21,516 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:21,519 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:21,531 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:21,540 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:21,545 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,424 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/css/css-index.css
2018-07-02 13:34:22,426 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/logo.png
2018-07-02 13:34:22,429 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,465 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,466 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,468 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:34:22,480 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/custom.js
2018-07-02 13:34:22,483 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/bg.jpg
2018-07-02 13:34:22,490 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/img/loading.GIF
2018-07-02 13:34:22,498 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/jquery.sticky.js
2018-07-02 13:34:22,506 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/wow.min.js
2018-07-02 13:34:22,509 [django.request:93] [base:get_response] [WARNING]- Not Found: /static/assets/js/owl.carousel.min.js
2018-07-02 13:35:30,488 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:48:28,352 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:53:41,984 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:53:49,147 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:/HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:/HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:/HttpRunnerManager\ApiManager\utils\common.py", line 439, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 13:54:04,117 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:54:07,459 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 13:57:09,661 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 13:57:11,824 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:39,039 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:04:44,830 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:04:54,650 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/test_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 379, in test_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:06:02,565 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/config_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 413, in config_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 432, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''
2018-07-02 14:24:14,328 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:24:16,921 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:27:17,963 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:44,949 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:27:47,983 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\template\base.py", line 475, in parse
    compile_func = self.tags[command]
KeyError: 'endif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 323, in project_list
    return render_to_response('project_list.html', manage_info)
  File "E:\Python35\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "E:\Python35\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 144, in get_template
    template, origin = self.find_template(template_name)
  File "E:\Python35\lib\site-packages\django\template\engine.py", line 126, in find_template
    template = loader.get_template(name, skip=skip)
  File "E:\Python35\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "E:\Python35\lib\site-packages\django\template\base.py", line 160, in __init__
    self.nodelist = self.compile_nodelist()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 198, in compile_nodelist
    return parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 290, in do_extends
    nodelist = parser.parse()
  File "E:\Python35\lib\site-packages\django\template\base.py", line 483, in parse
    raise self.error(token, e)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 481, in parse
    compiled_result = compile_func(self, token)
  File "E:\Python35\lib\site-packages\django\template\loader_tags.py", line 233, in do_block
    nodelist = parser.parse(('endblock',))
  File "E:\Python35\lib\site-packages\django\template\base.py", line 477, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "E:\Python35\lib\site-packages\django\template\base.py", line 533, in invalid_block_tag
    get_text_list(["'%s'" % p for p in parse_until], 'or'),
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 176: 'endif', expected 'endblock'. Did you forget to register or load this tag?
2018-07-02 14:28:16,257 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:28:18,192 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:16,138 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:20,563 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 311, in project_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 442, in set_filter_session
    'belong_project': request.session['project'],
  File "E:\Python35\lib\site-packages\django\contrib\sessions\backends\base.py", line 55, in __getitem__
    return self._session[key]
KeyError: 'project'
2018-07-02 14:37:24,899 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:37:26,773 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:37:30,837 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:37:33,775 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/add_case/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 170, in add_case
    msg = case_info_logic(**testcase_info)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 210, in case_info_logic
    test = kwargs.pop('test')
KeyError: 'test'
2018-07-02 14:39:25,603 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:39:27,918 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:43:42,829 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:43:44,932 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:47:52,728 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:47:54,981 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:55:50,890 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:55:53,036 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2018-07-02 14:57:17,859 [django.request:118] [exception:handle_uncaught_exception] [ERROR]- Internal Server Error: /api/module_list/1/
Traceback (most recent call last):
  File "E:\Python35\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\Python35\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager\ApiManager\views.py", line 345, in module_list
    filter_query = set_filter_session(request)
  File "D:\HttpRunnerManager\ApiManager\utils\common.py", line 433, in set_filter_session
    request.session['module'] = ModuleInfo.objects.get(id=request.POST.get('module')).module_name
  File "E:\Python35\lib\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 394, in get
    clone = self.filter(*args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "E:\Python35\lib\site-packages\django\db\models\query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1253, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1277, in _add_q
    split_subq=split_subq,
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1215, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "E:\Python35\lib\site-packages\django\db\models\sql\query.py", line 1085, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 18, in __init__
    self.rhs = self.get_prep_lookup()
  File "E:\Python35\lib\site-packages\django\db\models\lookups.py", line 68, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "E:\Python35\lib\site-packages\django\db\models\fields\__init__.py", line 947, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '用例_quant_login_out(登入登出)'
2018-07-02 14:59:50,449 [HttpRunnerManager:78] [views:log_out] [INFO]- yinquanwang退出
2018-07-02 14:59:52,333 [HttpRunnerManager:45] [views:login] [INFO]- yinquanwang 登录成功
2020-08-17 17:17:13,934 [django.request:230] [log:log_response] [WARNING]- Not Found: /
2020-08-17 17:17:36,583 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 10, in process
    app = __import__("%s.views" % app)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 7, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
2020-08-17 17:18:37,945 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 10, in process
    app = __import__("%s.views" % app)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 7, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
2020-08-17 17:25:15,603 [django.request:230] [log:log_response] [WARNING]- Not Found: /
2020-08-17 17:25:17,845 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 10, in process
    app = __import__("%s.views" % app)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 17, in <module>
    from ApiManager.tasks import main_hrun
  File "D:\HttpRunnerManager-master\ApiManager\tasks.py", line 16, in <module>
    from httprunner import HttpRunner, logger
ImportError: cannot import name 'logger' from 'httprunner' (D:\HttpRunnerTestVenv\lib\site-packages\httprunner\__init__.py)
2020-08-17 17:44:02,467 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 78, in register
    return render("register.html")
TypeError: render() missing 1 required positional argument: 'template_name'
2020-08-17 17:44:03,533 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 78, in register
    return render("register.html")
TypeError: render() missing 1 required positional argument: 'template_name'
2020-08-17 17:45:51,199 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/register/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 78, in register
    return render(request, "register.html")
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
2020-08-17 17:54:35,218 [HttpRunnerManager:35] [operation:add_register_data] [INFO]- 新增用户：ApiManager.UserInfo.objects
2020-08-17 17:54:37,355 [HttpRunnerManager:55] [views:login] [INFO]- wuwei 登录成功
2020-08-17 17:54:37,428 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/index/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 122, in index
    return render(request,'index.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
2020-08-17 18:01:19,620 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/project_list/1/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'staticfiles'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 315, in project_list
    return render(request,'project_list.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 270, in do_extends
    nodelist = parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'staticfiles' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
custom_tags
i18n
l10n
log
static
tz
2020-08-17 18:16:25,914 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/css/amazeui.min.css
2020-08-17 18:16:25,916 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/js/amazeui.min.js
2020-08-17 18:16:25,969 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/css/amazeui.min.css
2020-08-17 18:16:25,970 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/js/amazeui.min.js
2020-08-17 18:16:27,036 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/css/amazeui.min.css
2020-08-17 18:16:27,037 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/js/amazeui.min.js
2020-08-17 18:16:27,081 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/js/amazeui.min.js
2020-08-17 18:16:27,082 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/css/amazeui.min.css
2020-08-17 18:16:33,411 [django.request:230] [log:log_response] [WARNING]- Not Found: /api/add_project/static/amazeui/assets/css/amazeui.min.css
2020-08-17 18:19:08,824 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/add_project/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 142, in add_project
    return render(request,'add_project.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''/amazeui/assets/css/amazeui.min.css' from ''/amazeui/assets/css/amazeui.min.css'
2020-08-17 18:19:11,720 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/add_project/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 142, in add_project
    return render(request,'add_project.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''/amazeui/assets/css/amazeui.min.css' from ''/amazeui/assets/css/amazeui.min.css'
2020-08-17 18:19:20,843 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/add_project/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 142, in add_project
    return render(request,'add_project.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''amazeui/assets/css/amazeui.min.css' from ''amazeui/assets/css/amazeui.min.css'
2020-08-17 18:19:22,378 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/add_project/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
  File "D:\HttpRunnerManager-master\ApiManager\views.py", line 142, in add_project
    return render(request,'add_project.html', manage_info)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loader_tags.py", line 104, in find_template
    template_name, skip=history,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 159, in do_static
    return StaticNode.handle_token(parser, token)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\templatetags\static.py", line 133, in handle_token
    path = parser.compile_filter(bits[1])
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\template\base.py", line 663, in __init__
    "from '%s'" % (token[upto:], token))
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''amazeui/assets/css/amazeui.min.css' from ''amazeui/assets/css/amazeui.min.css'
2020-08-17 18:32:28,767 [django.request:230] [log:log_response] [WARNING]- Not Found: /
2020-08-17 18:32:39,838 [django.request:230] [log:log_response] [WARNING]- Not Found: /
2020-08-17 18:32:41,160 [django.request:230] [log:log_response] [WARNING]- Not Found: /
2020-08-17 18:32:43,933 [django.request:230] [log:log_response] [ERROR]- Internal Server Error: /api/project_list/
Traceback (most recent call last):
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\HttpRunnerTestVenv\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\httprunnermanagerTest\HttpRunnerManager-master\HttpRunnerManager\activator.py", line 15, in process
    result = fun(request, index) if index else fun(request)
  File "D:\httprunnermanagerTest\HttpRunnerManager-master\ApiManager\views.py", line 39, in wrapper
    return func(request, *args, **kwargs)
TypeError: project_list() missing 1 required positional argument: 'id'
2020-08-17 18:32:49,488 [django.request:230] [log:log_response] [WARNING]- Not Found: /api
2020-08-17 18:32:52,967 [django.request:230] [log:log_response] [WARNING]- Not Found: /index
2020-08-17 18:33:11,986 [HttpRunnerManager:55] [views:login] [INFO]- wuwei 登录成功
